export declare const internalProperties: string[];
export declare const internalPropertiesLang: {
    pID: string;
    pName: string;
    pStart: string;
    pEnd: string;
    pLink: string;
    pMile: string;
    pRes: string;
    pComp: string;
    pGroup: string;
    pParent: string;
    pOpen: string;
    pDepend: string;
    pCaption: string;
    pNotes: string;
    pCost: string;
    pPlanStart: string;
    pPlanEnd: string;
};
export declare function findObj(theObj: any, theDoc?: any): any;
export declare function stripIds(pNode: any): void;
export declare function stripUnwanted(pNode: any): void;
export declare function delayedHide(pGanttChartObj: any, pTool: any, pTimer: any): void;
export declare function getZoomFactor(): number;
export declare function benchMark(pItem: any): void;
export declare function getScrollPositions(): {
    x: number;
    y: number;
};
export declare function getScrollbarWidth(): any;
export declare function calculateCurrentDateOffset(curTaskStart: any, curTaskEnd: any): number;
export declare function getOffset(pStartDate: any, pEndDate: any, pColWidth: any, pFormat: any, pShowWeekends: any): number;
export declare function hideToolTip(pGanttChartObj: any, pTool: any, pTimer: any): void;
export declare function fadeToolTip(pDirection: any, pTool: any, pMaxAlpha: any): void;
export declare function hashString(key: any): number;
export declare function hashKey(key: any): number;
export declare function criticalPath(tasks: any): void;
export declare function isParentElementOrSelf(child: any, parent: any): boolean;
export declare function updateFlyingObj(e: any, pGanttChartObj: any, pTimer: any): void;
export declare function moveToolTip(pNewX: any, pNewY: any, pTool: any, timer: any): void;
export declare function makeRequest(pFile: any, json?: boolean, vDebug?: boolean): Promise<any>;
export declare function makeRequestOldBrowsers(pFile: any, vDebug?: boolean): Promise<unknown>;
