export interface GanttLanguage {
  format: string;
  hour: string;
  day: string;
  week: string;
  month: string;
  quarter: string;
  hours: string;
  days: string;
  weeks: string;
  months: string;
  quarters: string;
  hr: string;
  dy: string;
  wk: string;
  mth: string;
  qtr: string;
  hrs: string;
  dys: string;
  wks: string;
  mths: string;
  qtrs: string;
  res: string;
  dur: string;
  comp: string;
  completion: string;
  startdate: string;
  planstartdate: string;
  enddate: string;
  planenddate: string;
  duration: string
  resource: string
  cost: string;
  moreinfo: string;
  nodata: string;
  notes: string;
  january: string;
  february: string;
  march: string;
  april: string;
  maylong: string;
  june: string;
  july: string;
  august: string;
  september: string;
  october: string;
  november: string;
  december: string;
  jan: string;
  feb: string;
  mar: string;
  apr: string;
  may: string;
  jun: string;
  jul: string;
  aug: string;
  sep: string;
  oct: string;
  nov: string;
  dec: string;
  sunday: string;
  monday: string;
  tuesday: string;
  wednesday: string;
  thursday: string;
  friday: string;
  saturday: string;
  sun: string;
  mon: string;
  tue: string;
  wed: string;
  thu: string;
  fri: string;
  sat: string;
  tooltipLoading: string;
}

const en: GanttLanguage = {
  format: 'Format',
  hour: 'Hour',
  day: 'Day',
  week: 'Week',
  month: 'Month',
  quarter: 'Quarter',
  hours: 'Hours',
  days: 'Days',
  weeks: 'Weeks',
  months: 'Months',
  quarters: 'Quarters',
  hr: 'Hr',
  dy: 'Day',
  wk: 'Wk',
  mth: 'Mth',
  qtr: 'Qtr',
  hrs: 'Hrs',
  dys: 'Days',
  wks: 'Wks',
  mths: 'Mths',
  qtrs: 'Qtrs',
  res: 'Resource',
  dur: 'Duration',
  comp: '% Comp.',
  completion: 'Completion',
  startdate: 'Start Date',
  planstartdate: 'Plan Start Date',
  enddate: 'End Date',
  planenddate: 'Plan End Date',
  duration: 'Duration',
  resource: 'Resource',
  cost: 'Cost',
  moreinfo: 'More Information',
  nodata: 'No tasks found',
  notes: 'Notes',
  january: 'January',
  february: 'February',
  march: 'March',
  april: 'April',
  maylong: 'May',
  june: 'June',
  july: 'July',
  august: 'August',
  september: 'September',
  october: 'October',
  november: 'November',
  december: 'December',
  jan: 'Jan',
  feb: 'Feb',
  mar: 'Mar',
  apr: 'Apr',
  may: 'May',
  jun: 'Jun',
  jul: 'Jul',
  aug: 'Aug',
  sep: 'Sep',
  oct: 'Oct',
  nov: 'Nov',
  dec: 'Dec',
  sunday: 'Sunday',
  monday: 'Monday',
  tuesday: 'Tuesday',
  wednesday: 'Wednesday',
  thursday: 'Thursday',
  friday: 'Friday',
  saturday: 'Saturday',
  sun: 'Sun',
  mon: 'Mon',
  tue: 'Tue',
  wed: 'Wed',
  thu: 'Thu',
  fri: 'Fri',
  sat: 'Sat',
  tooltipLoading: 'Loading...'
};

const cn: GanttLanguage = {
  january: '一月',
  february: '二月',
  march: '三月',
  april: '四月',
  maylong: '五月',
  june: '六月',
  july: '七月',
  august: '八月',
  september: '九月',
  october: '十月',
  november: '十一月',
  december: '十二月',
  jan: '一月',
  feb: '二月',
  mar: '三月',
  apr: '四月',
  may: '五月',
  jun: '六月',
  jul: '七月',
  aug: '八月',
  sep: '九月',
  oct: '十月',
  nov: '十一',
  dec: '十二',
  sunday: '星期日',
  monday: '星期一',
  tuesday: '星期二',
  wednesday: '星期三',
  thursday: '星期四',
  friday: '星期五',
  saturday: '星期六',
  sun: '日',
  mon: '一',
  tue: '二',
  wed: '三',
  thu: '四',
  fri: '五',
  sat: '六',
  res: '资源',
  dur: '用时',
  comp: '完成率',
  completion: '已完成',
  startdate: '起始日期',
  planstartdate: '计划起始日期',
  enddate: '结束日期',
  planenddate: '计划结束日期',
  cost: '成本',
  duration: '用时',
  resource: '资源',
  moreinfo: '更多信息',
  nodata: '没有任何任务数据',
  notes: '备注',
  format: '格式',
  hour: '时',
  day: '日',
  week: '星期',
  month: '月',
  quarter: '季',
  hours: '小时',
  days: '天',
  weeks: '周',
  months: '月',
  quarters: '季',
  hr: '小时',
  dy: '天',
  wk: '周',
  mth: '月',
  qtr: '季',
  hrs: '小时',
  dys: '天',
  wks: '周',
  mths: '月',
  qtrs: '季',
  tooltipLoading: '加载中'
};

export const lang: Record<string, GanttLanguage> = {en, cn};
